### ISSUE TITLE
Inline Badge

### ISSUE THREAD

**Issue by gustavotrott** [gkTim/inkdrop-tag-badge#1]
Hello,

When I try to use a badge it always break the line.
I would like to put a badge inside a text for example...

What about using tag `Span` instead of `Div` for the badge?
Then it could be used in `inline` mode.

Thank you,
Gustavo

**Comment by gkTim** [comment]
Hi,

good point. 
I‘m currently on holiday  but after that I will change it. 

Thanks for your feedback.

**Comment by gkTim** [comment]
@gustavotrott With version 1.3.0 you are now able to use inline badges.
Thanks for your feedback!
